repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: flake8
    -   id: trailing-whitespace

-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/gklein/check_signoff
    rev: v1.0.4
    hooks:
    - id: check-signoff
      language_version: python3.7
